/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root"
import { Route as publicPublicRouteImport } from "./../routes/(public)/_public"
import { Route as authAuthRouteImport } from "./../routes/(auth)/_auth"
import { Route as appAppRouteImport } from "./../routes/(app)/_app"
import { Route as adminAdminRouteImport } from "./../routes/(admin)/_admin"
import { Route as publicPublicIndexRouteImport } from "./../routes/(public)/_public.index"
import { Route as publicPublicVerifyEmailRouteImport } from "./../routes/(public)/_public.verify-email"
import { Route as authAuthRegisterRouteImport } from "./../routes/(auth)/_auth.register"
import { Route as authAuthLoginRouteImport } from "./../routes/(auth)/_auth.login"
import { Route as appAppQuranRouteImport } from "./../routes/(app)/_app.quran"
import { Route as appAppHadistRouteImport } from "./../routes/(app)/_app.hadist"
import { Route as appAppGroupsRouteImport } from "./../routes/(app)/_app.groups"
import { Route as appAppFeedRouteImport } from "./../routes/(app)/_app.feed"
import { Route as appAppExploreRouteImport } from "./../routes/(app)/_app.explore"
import { Route as appAppUsernameRouteImport } from "./../routes/(app)/_app.$username"
import { Route as adminAdminAdminRouteImport } from "./../routes/(admin)/_admin.admin"
import { Route as appAppSettingsProfileRouteImport } from "./../routes/(app)/_app.settings.profile"
import { Route as appAppSettingsAccountRouteImport } from "./../routes/(app)/_app.settings.account"
import { Route as appAppUsernameFollowingRouteImport } from "./../routes/(app)/_app.$username.following"
import { Route as appAppUsernameFollowersRouteImport } from "./../routes/(app)/_app.$username.followers"

const publicPublicRoute = publicPublicRouteImport.update({
  id: "/(public)/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: "/(auth)/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: "/(app)/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRoute = adminAdminRouteImport.update({
  id: "/(admin)/_admin",
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicVerifyEmailRoute = publicPublicVerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => publicPublicRoute,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authAuthRoute,
} as any)
const appAppQuranRoute = appAppQuranRouteImport.update({
  id: "/quran",
  path: "/quran",
  getParentRoute: () => appAppRoute,
} as any)
const appAppHadistRoute = appAppHadistRouteImport.update({
  id: "/hadist",
  path: "/hadist",
  getParentRoute: () => appAppRoute,
} as any)
const appAppGroupsRoute = appAppGroupsRouteImport.update({
  id: "/groups",
  path: "/groups",
  getParentRoute: () => appAppRoute,
} as any)
const appAppFeedRoute = appAppFeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => appAppRoute,
} as any)
const appAppExploreRoute = appAppExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => appAppRoute,
} as any)
const appAppUsernameRoute = appAppUsernameRouteImport.update({
  id: "/$username",
  path: "/$username",
  getParentRoute: () => appAppRoute,
} as any)
const adminAdminAdminRoute = adminAdminAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => adminAdminRoute,
} as any)
const appAppSettingsProfileRoute = appAppSettingsProfileRouteImport.update({
  id: "/settings/profile",
  path: "/settings/profile",
  getParentRoute: () => appAppRoute,
} as any)
const appAppSettingsAccountRoute = appAppSettingsAccountRouteImport.update({
  id: "/settings/account",
  path: "/settings/account",
  getParentRoute: () => appAppRoute,
} as any)
const appAppUsernameFollowingRoute = appAppUsernameFollowingRouteImport.update({
  id: "/following",
  path: "/following",
  getParentRoute: () => appAppUsernameRoute,
} as any)
const appAppUsernameFollowersRoute = appAppUsernameFollowersRouteImport.update({
  id: "/followers",
  path: "/followers",
  getParentRoute: () => appAppUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  "/admin": typeof adminAdminAdminRoute
  "/$username": typeof appAppUsernameRouteWithChildren
  "/explore": typeof appAppExploreRoute
  "/feed": typeof appAppFeedRoute
  "/groups": typeof appAppGroupsRoute
  "/hadist": typeof appAppHadistRoute
  "/quran": typeof appAppQuranRoute
  "/login": typeof authAuthLoginRoute
  "/register": typeof authAuthRegisterRoute
  "/verify-email": typeof publicPublicVerifyEmailRoute
  "/": typeof publicPublicIndexRoute
  "/$username/followers": typeof appAppUsernameFollowersRoute
  "/$username/following": typeof appAppUsernameFollowingRoute
  "/settings/account": typeof appAppSettingsAccountRoute
  "/settings/profile": typeof appAppSettingsProfileRoute
}
export interface FileRoutesByTo {
  "/admin": typeof adminAdminAdminRoute
  "/$username": typeof appAppUsernameRouteWithChildren
  "/explore": typeof appAppExploreRoute
  "/feed": typeof appAppFeedRoute
  "/groups": typeof appAppGroupsRoute
  "/hadist": typeof appAppHadistRoute
  "/quran": typeof appAppQuranRoute
  "/login": typeof authAuthLoginRoute
  "/register": typeof authAuthRegisterRoute
  "/verify-email": typeof publicPublicVerifyEmailRoute
  "/": typeof publicPublicIndexRoute
  "/$username/followers": typeof appAppUsernameFollowersRoute
  "/$username/following": typeof appAppUsernameFollowingRoute
  "/settings/account": typeof appAppSettingsAccountRoute
  "/settings/profile": typeof appAppSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(admin)/_admin": typeof adminAdminRouteWithChildren
  "/(app)/_app": typeof appAppRouteWithChildren
  "/(auth)/_auth": typeof authAuthRouteWithChildren
  "/(public)/_public": typeof publicPublicRouteWithChildren
  "/(admin)/_admin/admin": typeof adminAdminAdminRoute
  "/(app)/_app/$username": typeof appAppUsernameRouteWithChildren
  "/(app)/_app/explore": typeof appAppExploreRoute
  "/(app)/_app/feed": typeof appAppFeedRoute
  "/(app)/_app/groups": typeof appAppGroupsRoute
  "/(app)/_app/hadist": typeof appAppHadistRoute
  "/(app)/_app/quran": typeof appAppQuranRoute
  "/(auth)/_auth/login": typeof authAuthLoginRoute
  "/(auth)/_auth/register": typeof authAuthRegisterRoute
  "/(public)/_public/verify-email": typeof publicPublicVerifyEmailRoute
  "/(public)/_public/": typeof publicPublicIndexRoute
  "/(app)/_app/$username/followers": typeof appAppUsernameFollowersRoute
  "/(app)/_app/$username/following": typeof appAppUsernameFollowingRoute
  "/(app)/_app/settings/account": typeof appAppSettingsAccountRoute
  "/(app)/_app/settings/profile": typeof appAppSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/admin"
    | "/$username"
    | "/explore"
    | "/feed"
    | "/groups"
    | "/hadist"
    | "/quran"
    | "/login"
    | "/register"
    | "/verify-email"
    | "/"
    | "/$username/followers"
    | "/$username/following"
    | "/settings/account"
    | "/settings/profile"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/admin"
    | "/$username"
    | "/explore"
    | "/feed"
    | "/groups"
    | "/hadist"
    | "/quran"
    | "/login"
    | "/register"
    | "/verify-email"
    | "/"
    | "/$username/followers"
    | "/$username/following"
    | "/settings/account"
    | "/settings/profile"
  id:
    | "__root__"
    | "/(admin)/_admin"
    | "/(app)/_app"
    | "/(auth)/_auth"
    | "/(public)/_public"
    | "/(admin)/_admin/admin"
    | "/(app)/_app/$username"
    | "/(app)/_app/explore"
    | "/(app)/_app/feed"
    | "/(app)/_app/groups"
    | "/(app)/_app/hadist"
    | "/(app)/_app/quran"
    | "/(auth)/_auth/login"
    | "/(auth)/_auth/register"
    | "/(public)/_public/verify-email"
    | "/(public)/_public/"
    | "/(app)/_app/$username/followers"
    | "/(app)/_app/$username/following"
    | "/(app)/_app/settings/account"
    | "/(app)/_app/settings/profile"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminAdminRoute: typeof adminAdminRouteWithChildren
  appAppRoute: typeof appAppRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(public)/_public": {
      id: "/(public)/_public"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof publicPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/_auth": {
      id: "/(auth)/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/_app": {
      id: "/(app)/_app"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(admin)/_admin": {
      id: "/(admin)/_admin"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof adminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(public)/_public/": {
      id: "/(public)/_public/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    "/(public)/_public/verify-email": {
      id: "/(public)/_public/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof publicPublicVerifyEmailRouteImport
      parentRoute: typeof publicPublicRoute
    }
    "/(auth)/_auth/register": {
      id: "/(auth)/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    "/(auth)/_auth/login": {
      id: "/(auth)/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    "/(app)/_app/quran": {
      id: "/(app)/_app/quran"
      path: "/quran"
      fullPath: "/quran"
      preLoaderRoute: typeof appAppQuranRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/hadist": {
      id: "/(app)/_app/hadist"
      path: "/hadist"
      fullPath: "/hadist"
      preLoaderRoute: typeof appAppHadistRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/groups": {
      id: "/(app)/_app/groups"
      path: "/groups"
      fullPath: "/groups"
      preLoaderRoute: typeof appAppGroupsRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/feed": {
      id: "/(app)/_app/feed"
      path: "/feed"
      fullPath: "/feed"
      preLoaderRoute: typeof appAppFeedRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/explore": {
      id: "/(app)/_app/explore"
      path: "/explore"
      fullPath: "/explore"
      preLoaderRoute: typeof appAppExploreRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/$username": {
      id: "/(app)/_app/$username"
      path: "/$username"
      fullPath: "/$username"
      preLoaderRoute: typeof appAppUsernameRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(admin)/_admin/admin": {
      id: "/(admin)/_admin/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof adminAdminAdminRouteImport
      parentRoute: typeof adminAdminRoute
    }
    "/(app)/_app/settings/profile": {
      id: "/(app)/_app/settings/profile"
      path: "/settings/profile"
      fullPath: "/settings/profile"
      preLoaderRoute: typeof appAppSettingsProfileRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/settings/account": {
      id: "/(app)/_app/settings/account"
      path: "/settings/account"
      fullPath: "/settings/account"
      preLoaderRoute: typeof appAppSettingsAccountRouteImport
      parentRoute: typeof appAppRoute
    }
    "/(app)/_app/$username/following": {
      id: "/(app)/_app/$username/following"
      path: "/following"
      fullPath: "/$username/following"
      preLoaderRoute: typeof appAppUsernameFollowingRouteImport
      parentRoute: typeof appAppUsernameRoute
    }
    "/(app)/_app/$username/followers": {
      id: "/(app)/_app/$username/followers"
      path: "/followers"
      fullPath: "/$username/followers"
      preLoaderRoute: typeof appAppUsernameFollowersRouteImport
      parentRoute: typeof appAppUsernameRoute
    }
  }
}

interface adminAdminRouteChildren {
  adminAdminAdminRoute: typeof adminAdminAdminRoute
}

const adminAdminRouteChildren: adminAdminRouteChildren = {
  adminAdminAdminRoute: adminAdminAdminRoute,
}

const adminAdminRouteWithChildren = adminAdminRoute._addFileChildren(
  adminAdminRouteChildren,
)

interface appAppUsernameRouteChildren {
  appAppUsernameFollowersRoute: typeof appAppUsernameFollowersRoute
  appAppUsernameFollowingRoute: typeof appAppUsernameFollowingRoute
}

const appAppUsernameRouteChildren: appAppUsernameRouteChildren = {
  appAppUsernameFollowersRoute: appAppUsernameFollowersRoute,
  appAppUsernameFollowingRoute: appAppUsernameFollowingRoute,
}

const appAppUsernameRouteWithChildren = appAppUsernameRoute._addFileChildren(
  appAppUsernameRouteChildren,
)

interface appAppRouteChildren {
  appAppUsernameRoute: typeof appAppUsernameRouteWithChildren
  appAppExploreRoute: typeof appAppExploreRoute
  appAppFeedRoute: typeof appAppFeedRoute
  appAppGroupsRoute: typeof appAppGroupsRoute
  appAppHadistRoute: typeof appAppHadistRoute
  appAppQuranRoute: typeof appAppQuranRoute
  appAppSettingsAccountRoute: typeof appAppSettingsAccountRoute
  appAppSettingsProfileRoute: typeof appAppSettingsProfileRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppUsernameRoute: appAppUsernameRouteWithChildren,
  appAppExploreRoute: appAppExploreRoute,
  appAppFeedRoute: appAppFeedRoute,
  appAppGroupsRoute: appAppGroupsRoute,
  appAppHadistRoute: appAppHadistRoute,
  appAppQuranRoute: appAppQuranRoute,
  appAppSettingsAccountRoute: appAppSettingsAccountRoute,
  appAppSettingsProfileRoute: appAppSettingsProfileRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface publicPublicRouteChildren {
  publicPublicVerifyEmailRoute: typeof publicPublicVerifyEmailRoute
  publicPublicIndexRoute: typeof publicPublicIndexRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicVerifyEmailRoute: publicPublicVerifyEmailRoute,
  publicPublicIndexRoute: publicPublicIndexRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminAdminRoute: adminAdminRouteWithChildren,
  appAppRoute: appAppRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
  publicPublicRoute: publicPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
